FROM golang:1.13 as build
ENV CGO_ENABLED 0
ENV GOPATH /go
COPY . /go/src/github.com/m-lab/gcs-exporter/
WORKDIR /go/src/github.com/m-lab/gcs-exporter/
# Get test dependencies & run tests.
RUN go get -t -v ./
RUN go get -t -v ./gcs/
RUN go test -v ./...
